Repository gardener/scaling-advisor, pull requests merged in 2025-09, with the labels that each got.

#44 Refactor pricing and scoring modules to work with one another
  service/api/errors.go
  service/api/types.go
  service/internal/service/generator/generator.go
  service/internal/service/service.go
  service/pricing/pricing.go
  service/pricing/pricing_test/pricing_test.go
  service/pricing/test_instances.json
  service/pricing/testutil/testdata/instance_type_infos.json
  service/pricing/testutil/testutil.go
  service/scorer/scorer.go
  service/scorer/scorer_test.go
Labels: needs/review, needs/second-opinion, size/l

#57 [FIX] Pass correct struct for advisor server configuration in `cli_test`
  operator/cmd/scalingadvisor/cli/cli_test.go
Labels: needs/review, size/xs

#58 Prerequites for minkapi in-memory clients
  api/common/errors/errors.go
  api/common/types/types.go
  api/minkapi/errors.go
  api/minkapi/types.go
  api/minkapi/types_test.go
  common/clientutil/clientutil.go
  common/objutil/objutil.go
  common/objutil/objutil_test.go
  common/watchutil/watchutil.go
  minkapi/server/inmclient/appsv1.go
  minkapi/server/inmclient/client.go
  minkapi/server/inmclient/corev1.go
  minkapi/server/inmclient/replicaset.go
  minkapi/server/inmclient/util.go
  minkapi/server/server.go
  minkapi/server/store/store.go
  minkapi/server/store/store_test.go
  minkapi/server/view/base.go
  minkapi/server/view/base_test.go
  minkapi/server/view/sandbox.go
  service/scorer/scorer_test.go
Labels: needs/review, needs/second-opinion, size/xl

#62 Added non-release workflow github actions that uses build.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
Labels: reviewed/lgtm, size/xs

#63 Add +x permissions for `hack/sast.sh`, `hack/tools/install-gosec.sh` and added `VERSION` file
  VERSION
  hack/sast.sh
  hack/tools/install-gosec.sh
Labels: needs/review, size/xs

#65 Remove unbound variable from `hack/sast.sh`
  hack/sast.sh
Labels: needs/review, size/xs

#69 ci: add pr write permission to all jobs running trusted-checkout
  .github/workflows/build.yaml
Labels: needs/review, size/xs, status/accepted
